### ISSUE TITLE
Pick your numerical methods to code

### ISSUE THREAD

**Issue by omaraltayyan** [omaraltayyan/NumericalAnalysis#1]
we need every one in the team to write two or more numerical methods to code, so that we avoid having one guy do all the hard work, and we all collaborate to achieve justice and good behavior between us, and fine tuned coding and testing, since 2 brains are better than one and 3 brains are better that 2 :smirk:

**Comment by omaraltayyan** [comment]
i have coded the General method, and will do hermit's as well.

**Comment by omaraltayyan** [comment]
i'll do Lagrange's method as well, since it's a small part of Hermit's method.

**Comment by omaraltayyan** [comment]
important NOTE: always make a new branch when making one of your method, when you're done, make a pull request to merge you branch with the master branch, DON'T CODE DIRECTLY TO THE MASTER BRANCH!!!!!

**Comment by Hatem-Hamad** [comment]
i'll do the Newton Divided Differences both Progressive and Regressive

**Comment by omaraltayyan** [comment]
OK great :+1: @Hatem-Hamad @Muhammad-Ayoub-94  , a quick reminder: Don't forget to create you're own branch, don't push to master until your code is tested and ready
